"""add rent

Revision ID: 1b8014405e21
Revises: 4f0214eb0241
Create Date: 2024-08-13 23:05:27.029080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b8014405e21'
down_revision = '4f0214eb0241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organizer_id', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('rent_date', sa.DateTime(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], name=op.f('fk_rents_organizer_id_organizers')),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_rents_venue_id_venues')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paymentsorganizer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('rent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rent_id'], ['rents.id'], name=op.f('fk_paymentsorganizer_rent_id_rents')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.drop_column('venue_price')

    op.drop_table('paymentsorganizer')
    op.drop_table('rents')
    # ### end Alembic commands ###
