"""added order id and ticket

Revision ID: 4cc06b1cf95a
Revises: 094c9441612b
Create Date: 2024-08-10 10:33:27.399509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cc06b1cf95a'
down_revision = '094c9441612b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tickets_order_id_orders'), 'orders', ['order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tickets_order_id_orders'), type_='foreignkey')
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###
