"""changed ticket

Revision ID: bb6081371ad4
Revises: 6990a89ec02e
Create Date: 2024-08-09 14:32:49.662633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb6081371ad4'
down_revision = '6990a89ec02e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tickets_event_id_events'), 'events', ['event_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tickets_event_id_events'), type_='foreignkey')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
